const fs = require('fs');

function isEntryPoint() {
  return require.main === module;
}

function collect(poFilename) {
    const data = new String(fs.readFileSync(poFilename)).split('\n');
    let result = {};

    let msgid = '';
    for (let i in data) {
        const line = data[i];
        if (!msgid) {
            if (line.startsWith('msgid')) {
                msgid = line.substring(7, line.length);
                msgid = msgid.substring(0, msgid.length - 1);
            }
        } else {
            if (line.startsWith('msgstr')) {
                let msgstr = line.substring(8, line.length);
                msgstr = msgstr.substring(0, msgstr.length - 1);
                result[msgid] = msgstr;
                msgid = '';
            }
        }
    }
    return result;
}

function convertAll(poFilenames, jsFilename) {
    let file = '//Autogenerated\nmodule.exports = {\n';
    for (let i in poFilenames) {
        const poFilename = poFilenames[i];
        let name = poFilename.split('.')[0];
        name = name.split(['/']);
        name = name[name.length - 1];
        const subRes = collect(poFilename);
        file += `"${name}": ` + JSON.stringify(subRes) + ',\n';
    }
    file += '}\n';
    fs.writeFileSync(jsFilename, file);
}

module.exports = convertAll;

if (isEntryPoint()) {
    const length = process.argv.length;
    if (length < 4) {
        console.log("po2js input_file output_file");
        process.exit(1);
    }

    convertAll(process.argv.slice(2, length - 1), process.argv[length - 1]);
    process.exit(0);
}

